### PR TITLE
Enhance BT algorithms by moving the AbilitySystemComponent to Enemy

### PR DESCRIPTION
**Pull request by gerardparareda**
## IMP

Enhance BT algorithms by moving the AbilitySystemComponent (and other components) to Enemy.h instead of inherited instances.

### Code
- Source/RogueLight/AI/BTDec/BTDec_AttackType.cpp
- Source/RogueLight/AI/BTDec/BTDec_CheckGameplayTag.cpp
- Source/RogueLight/AI/BTDec/BTDec_PlayerFound.cpp
- Source/RogueLight/AI/BTTask/BTTask_ApplyDamage.cpp
- Source/RogueLight/AI/BTTask/BTTask_DistanceCheck.cpp
- Source/RogueLight/AI/BTTask/BTTask_Explode.cpp
- Source/RogueLight/AI/BTTask/BTTask_LaunchProjectile.cpp
- Source/RogueLight/AI/BTTask/BTTask_ProcessImpact.cpp
- Source/RogueLight/AI/BTTask/BTTask_Teleport.cpp
- Source/RogueLight/Character/RL_Aurora.cpp
- Source/RogueLight/Character/RL_Enemy.cpp
- Source/RogueLight/Character/RL_Enemy.h
- Source/RogueLight/Character/RL_Enemy_Ambusher.cpp
- Source/RogueLight/Character/RL_Enemy_Ambusher.h
- Source/RogueLight/Character/RL_Enemy_Consumer.cpp
- Source/RogueLight/Character/RL_Enemy_Consumer.h
- Source/RogueLight/Character/RL_Enemy_Raider.cpp
- Source/RogueLight/Character/RL_Enemy_Raider.h
- Source/RogueLight/Character/RL_Enemy_Tank.cpp
- Source/RogueLight/Character/RL_Enemy_Tank.h

### CODE REVIEW

**Comment by gerardparareda** [comment]
He provat els enemics en el mapa de proves (afegint el EnemyManager) i funcionen.

**Review by rceci64 — DISMISSED** [review]
Seems nice. No tinc l'Unreal a mà per provar però té bona pinta. Jo esperaria a que en @SergiBaldi ho acabi de mirar que ell ho tenia més per mà.

**Review by SergiBaldi — DISMISSED** [review]
Sembla que te bona pinta

**Review by SergiBaldi — APPROVED** [review]
Sembla que te bona pinta

**Pull request merged**
